version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: server
    main: ./cmd/mcp-go
    binary: mcp-go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Optimize build flags for size and performance
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath
    # Enable parallel builds
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: default
    formats: [ 'zip', 'tar.gz']
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: inja-online
    name: golang-mcp
  draft: false
  prerelease: auto

